basic.showIcon(IconNames.Heart)
basic.forever(function () {
    OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Run)
    basic.pause(1000)
    OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Back)
    basic.pause(1000)
    OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Left)
    basic.pause(1000)
    OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Right)
    basic.pause(1000)
    OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Stop)
    basic.pause(1000)
    basic.showIcon(IconNames.Heart)
})
basic.forever(function () {
    basic.forever(function on_forever2() {
        OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Run)
        basic.pause(1000)
        OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Back)
        basic.pause(1000)
        OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Left)
        basic.pause(1000)
        OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Right)
        basic.pause(1000)
        OSOYOO_Robot.CarCtrl(OSOYOO_Robot.CarState.Car_Stop)
        basic.pause(1000)
    })
})
